name: Java Build

on: [push]

jobs:
  build:
    if: join(github.event.commits.*.message) != ''
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Gradle
        id: build
        env:
          LAST_COMMIT_MESSAGE: ${{ github.event.commits[0].message }}
        run: ./gradlew build --no-daemon
      - name: Save artifact
        if: steps.build.outputs.version == null
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Build result
          path: build/libs/
      - name: Create release
        id: create_release
        if: steps.build.outputs.version != null
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.build.outputs.version }}
          release_name: v${{ steps.build.outputs.version }}
          draft: false
          prerelease: false
      - name: Upload release asset
        id: upload-release-asset
        if: steps.build.outputs.version != null
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/libs/huesoaddons-${{ steps.build.outputs.version }}.jar
          asset_name: huesoaddons-${{ steps.build.outputs.version }}.jar
          asset_content_type: application/java-archive
